'use client';

import { useMemo, useState } from 'react';
import { formatMoney, formatPct, simulate } from '../lib/finance';
import type { Analysis, ScenarioInputs, Transaction } from '../lib/types';

const categories=['Housing','Debt','Groceries','Dining','Transport','Subscriptions','Utilities','Shopping','Insurance','Investment','Health','Income','Other'];
const download=(name:string,content:string,type='text/csv')=>{const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);};
const evidenceLabel={known:'Known from data',estimate:'Statistical estimate',simulation:'Simulation',heuristic:'Heuristic'} as const;

function CashChart({analysis,scenario}:{analysis:Analysis;scenario?:ScenarioInputs}){const data=scenario?simulate(analysis,scenario):analysis.forecast;if(!data.length)return null;const w=820,h=280,p={l:50,r:20,t:22,b:42};const vals=data.flatMap(d=>[d.lower,d.upper,d.cumulativeChange]);const min=Math.min(0,...vals),max=Math.max(1,...vals);const x=(i:number)=>p.l+(i/(Math.max(1,data.length-1)))*(w-p.l-p.r);const y=(v:number)=>p.t+(1-(v-min)/(max-min||1))*(h-p.t-p.b);const line=data.map((d,i)=>`${x(i)},${y(d.cumulativeChange)}`).join(' ');const area=[...data.map((d,i)=>`${x(i)},${y(d.upper)}`),...data.slice().reverse().map((d,ri)=>`${x(data.length-1-ri)},${y(d.lower)}`)].join(' ');return <div className="chart-shell"><svg viewBox={`0 0 ${w} ${h}`} className="cash-chart" role="img" aria-label="Six month cumulative cash-flow forecast"><line x1={p.l} x2={w-p.r} y1={y(0)} y2={y(0)} className="zero-line"/><polygon points={area} className="forecast-band"/><polyline points={line} className="forecast-line" fill="none"/>{data.map((d,i)=><g key={d.month} className="forecast-point"><circle cx={x(i)} cy={y(d.cumulativeChange)} r="5"><title>{`${d.month}: ${formatMoney(d.cumulativeChange)} cumulative change; plausible range ${formatMoney(d.lower)} to ${formatMoney(d.upper)}`}</title></circle><text x={x(i)} y={h-15} textAnchor="middle">{d.month.slice(5)}</text></g>)}</svg><div className="chart-legend"><span><i className="legend-line"/>Central estimate</span><span><i className="legend-band"/>Uncertainty band</span><span>Forecast is directional, not a guarantee.</span></div></div>}

export function Dashboard({analysis,sourceLabel,currentBalance,onBalance,onTransactions,onReset}:{analysis:Analysis;sourceLabel:string;currentBalance:number;onBalance:(n:number)=>void;onTransactions:(rows:Transaction[])=>void;onReset:()=>void}){
  const [tab,setTab]=useState<'overview'|'commitments'|'transactions'>('overview'); const [scenario,setScenario]=useState<ScenarioInputs>({monthlyIncomeChange:0,monthlyEmi:0,monthlyRentChange:0,oneTimeSpend:0,monthlyInvestment:0}); const [scenarioOn,setScenarioOn]=useState(false); const [query,setQuery]=useState('');
  const simulated=useMemo(()=>simulate(analysis,scenario),[analysis,scenario]); const baselineEnd=analysis.forecast.at(-1)?.cumulativeChange??0; const simEnd=simulated.at(-1)?.cumulativeChange??0;
  const visible=analysis.transactions.filter(r=>!query||`${r.merchant} ${r.description} ${r.category}`.toLowerCase().includes(query.toLowerCase())).slice().reverse().slice(0,80);
  function recategorize(row:Transaction,category:string){onTransactions(analysis.transactions.map(t=>t.merchant===row.merchant?{...t,category}:t));}
  function exportPlan(){const lines=[['Priority','Action','Detail','Amount','Evidence'],...analysis.actions.map(a=>[a.priority,a.title,a.detail,a.amount??'',evidenceLabel[a.evidence]])];download('financial-xray-action-plan.csv',lines.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n'));}
  function exportTransactions(){const lines=[['Date','Merchant','Description','Amount','Direction','Account','Category','Transfer','Unusual score'],...analysis.transactions.map(r=>[r.date,r.merchant,r.description,r.amount,r.direction,r.account,r.category,r.transferPairId?'yes':'no',(r.unusualScore??0).toFixed(2)])];download('financial-xray-clean-transactions.csv',lines.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n'));}
  const s=analysis.summary;
  return <main className="app"><header className="app-header"><nav><div className="brand"><span className="brand-mark">FX</span><span>Financial X-Ray</span></div><div className="nav-actions"><button className="btn btn--ghost-dark" onClick={exportPlan}>Export action plan</button><button className="btn btn--ghost-dark" onClick={onReset}>New analysis</button></div></nav><div className="header-grid"><div><p className="eyebrow eyebrow--light">Your financial trajectory</p><h1>If nothing changes,<br/><span>here is what happens next.</span></h1><p>{sourceLabel} · processed locally in this browser</p></div><div className="trajectory-card"><span>6-month projected cash-flow change</span><strong className={(analysis.forecast.at(-1)?.cumulativeChange??0)>=0?'positive-text':'negative-text'}>{formatMoney(analysis.forecast.at(-1)?.cumulativeChange??0)}</strong><small>Central estimate from recent monthly patterns and detected commitments.</small></div></div></header>
    <div className="shell"><div className="trust-strip"><span><i className="dot dot--known"/>Known from data</span><span><i className="dot dot--estimate"/>Statistical estimate</span><span><i className="dot dot--sim"/>Simulation</span><span><i className="dot dot--heur"/>Heuristic flag</span><p>Financial X-Ray deliberately separates facts from modelled conclusions.</p></div>
      <div className="tabs"><button className={tab==='overview'?'active':''} onClick={()=>setTab('overview')}>Overview</button><button className={tab==='commitments'?'active':''} onClick={()=>setTab('commitments')}>Commitments</button><button className={tab==='transactions'?'active':''} onClick={()=>setTab('transactions')}>Transactions</button></div>
      {tab==='overview'&&<>
        <section className="section"><div className="section-head"><div><p className="eyebrow">Decision snapshot</p><h2>Your money, translated into decisions</h2></div><label className="balance-editor"><span>Current cash balance</span><div><b>₹</b><input value={currentBalance||''} inputMode="numeric" onChange={e=>onBalance(Number(e.target.value)||0)} placeholder="optional"/></div></label></div><div className="kpi-grid"><article className="kpi kpi--hero"><span>Estimated safe to spend / month</span><strong>{formatMoney(s.safeToSpend)}</strong><p>After detected commitments and a conservative buffer for normal variable spend.</p><em>Estimate</em></article><article className="kpi"><span>Monthly income baseline</span><strong>{formatMoney(s.monthlyIncome)}</strong><p>Average across available months.</p><em>Known → aggregated</em></article><article className="kpi"><span>Monthly expense baseline</span><strong>{formatMoney(s.monthlyExpenses)}</strong><p>Internal transfers excluded.</p><em>Known → aggregated</em></article><article className="kpi"><span>Fixed commitments</span><strong>{formatMoney(s.fixedCommitments)}</strong><p>Monthly recurring + detected sinking-fund reserve.</p><em>Estimate</em></article><article className="kpi"><span>Income reliability</span><strong>{s.incomeReliability}/100</strong><p>Higher means monthly income is more stable in this dataset.</p><em>Heuristic</em></article><article className="kpi"><span>Suggested emergency buffer</span><strong>{s.emergencyBufferMonths.toFixed(1)} mo</strong><p>More variable income increases the target.</p><em>Heuristic</em></article></div></section>
        <section className="section split"><div className="panel panel--wide"><div className="panel-head"><div><p className="eyebrow">Six-month X-Ray</p><h2>{scenarioOn?'Your simulated trajectory':'Your baseline trajectory'}</h2></div><button className={`scenario-toggle ${scenarioOn?'on':''}`} onClick={()=>setScenarioOn(!scenarioOn)}><span/>Scenario {scenarioOn?'on':'off'}</button></div><CashChart analysis={analysis} scenario={scenarioOn?scenario:undefined}/>{scenarioOn&&<div className="scenario-delta"><span>Simulation changes 6-month cash position by</span><strong className={simEnd-baselineEnd>=0?'positive-text':'negative-text'}>{simEnd-baselineEnd>=0?'+':''}{formatMoney(simEnd-baselineEnd)}</strong></div>}</div><aside className="panel action-panel"><p className="eyebrow">Action queue</p><h2>What deserves attention</h2><div className="action-list">{analysis.actions.slice(0,5).map((a,i)=><article key={`${a.title}-${i}`} className={`action action--${a.priority}`}><div><span>{a.priority}</span><small>{evidenceLabel[a.evidence]}</small></div><strong>{a.title}</strong><p>{a.detail}</p></article>)}</div><button className="btn btn--primary btn--full" onClick={exportPlan}>Download action plan</button></aside></section>
        <section className="section"><div className="section-head"><div><p className="eyebrow">Decision simulator</p><h2>Stress-test a life change before you commit</h2><p>These are arithmetic scenarios on top of the forecast—not claims about future behaviour.</p></div><button className="btn btn--ghost" onClick={()=>{setScenario({monthlyIncomeChange:0,monthlyEmi:0,monthlyRentChange:0,oneTimeSpend:0,monthlyInvestment:0});setScenarioOn(true)}}>Reset</button></div><div className="simulator"><div className="sim-controls">{[
          ['monthlyIncomeChange','Monthly income change',-60000,60000,5000],['monthlyEmi','New monthly EMI',0,60000,2500],['monthlyRentChange','Monthly rent change',-20000,40000,2000],['monthlyInvestment','Monthly investment',0,60000,2500],['oneTimeSpend','One-time spend',0,500000,10000]
        ].map(([key,label,min,max,step])=><label key={String(key)}><div><span>{label}</span><strong>{formatMoney(scenario[key as keyof ScenarioInputs])}</strong></div><input type="range" min={Number(min)} max={Number(max)} step={Number(step)} value={scenario[key as keyof ScenarioInputs]} onChange={e=>{setScenarioOn(true);setScenario({...scenario,[key]:Number(e.target.value)})}}/></label>)}</div><div className="sim-output"><p className="eyebrow eyebrow--light">Simulated six-month outcome</p><strong>{formatMoney(simEnd)}</strong><span className={simEnd-baselineEnd>=0?'positive-text':'negative-text'}>{simEnd-baselineEnd>=0?'+':''}{formatMoney(simEnd-baselineEnd)} vs baseline</span><div className="sim-bars"><div><span>Baseline</span><i style={{width:`${Math.min(100,Math.abs(baselineEnd)/Math.max(1,Math.abs(baselineEnd),Math.abs(simEnd))*100)}%`}}/></div><div><span>Scenario</span><i style={{width:`${Math.min(100,Math.abs(simEnd)/Math.max(1,Math.abs(baselineEnd),Math.abs(simEnd))*100)}%`}}/></div></div><small>Simulation assumes the rest of your recent spending pattern remains broadly similar.</small></div></div></section>
      </>}
      {tab==='commitments'&&<><section className="section"><div className="section-head"><div><p className="eyebrow">Recurring commitments</p><h2>What keeps coming back</h2><p>Recurring detection uses timing and amount consistency. Confidence below 100% is intentional.</p></div></div><div className="cards-grid">{analysis.recurring.map(r=><article className="commit-card" key={r.id}><div><span className={`pill ${r.direction==='income'?'pill--good':''}`}>{r.direction}</span><span className="confidence">{Math.round(r.confidence*100)}% confidence</span></div><h3>{r.merchant}</h3><strong>{formatMoney(r.medianAmount)}</strong><p>Every ~{r.cadenceDays} days · next expected {r.nextExpectedDate}</p>{r.driftPct>0.08&&<div className="drift">↑ Latest amount about {formatPct(r.driftPct)} above prior baseline</div>}</article>)}</div></section><section className="section"><div className="section-head"><div><p className="eyebrow">Sinking funds</p><h2>Make annual bills monthly before they become surprises</h2></div></div>{analysis.sinkingFunds.length?<div className="cards-grid">{analysis.sinkingFunds.map(f=><article className="commit-card" key={f.merchant}><span className="pill pill--warm">non-monthly</span><h3>{f.merchant}</h3><strong>{formatMoney(f.monthlyReserve)} / mo</strong><p>Reserve toward ~{formatMoney(f.annualizedAmount)} annualized · expected around {f.expectedMonth}</p></article>)}</div>:<div className="empty">No high-confidence non-monthly recurring commitments were detected in this dataset.</div>}</section></>}
      {tab==='transactions'&&<section className="section"><div className="section-head"><div><p className="eyebrow">Clean transaction ledger</p><h2>Inspect and correct the analysis</h2><p>Recategorizing a merchant updates every matching transaction locally and recomputes the X-Ray.</p></div><div className="transaction-tools"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search merchant or category…"/><button className="btn btn--ghost" onClick={exportTransactions}>Export cleaned CSV</button></div></div><div className="table-wrap"><table><thead><tr><th>Date</th><th>Merchant</th><th>Amount</th><th>Account</th><th>Category</th><th>Signal</th></tr></thead><tbody>{visible.map(r=><tr key={r.id}><td>{r.date}</td><td><strong>{r.merchant}</strong><small>{r.description}</small></td><td className={r.direction==='income'?'positive-text':r.direction==='expense'?'negative-text':''}>{r.direction==='income'?'+':r.direction==='expense'?'-':''}{formatMoney(Math.abs(r.amount))}</td><td>{r.account}</td><td><select value={r.category} onChange={e=>recategorize(r,e.target.value)}>{Array.from(new Set([...categories,r.category])).map(c=><option key={c}>{c}</option>)}</select></td><td>{r.transferPairId?<span className="pill">internal transfer</span>:(r.unusualScore??0)>=3.5?<span className="pill pill--risk">unusual</span>:<span className="muted">—</span>}</td></tr>)}</tbody></table></div></section>}
      <section className="method-strip"><div><p className="eyebrow">Method honesty</p><h2>What this product knows—and what it does not</h2></div><div><strong>Known</strong><p>Your parsed transaction amounts, dates, accounts and the categories you confirm.</p></div><div><strong>Estimated</strong><p>Recurring cadence, merchant baselines, safe-to-spend and the cash-flow forecast.</p></div><div><strong>Not claimed</strong><p>No investment advice, fraud conclusion, credit decision or guaranteed future balance.</p></div></section>
    </div><footer><span>Day 02 · Financial X-Ray</span><span>Browser-local analysis · No bank linking · No account required</span></footer>
  </main>;
}
